version: '3.8'

services:

    simple-web-service:
      image: devopsdockeruh/simple-web-service/simple-web-service
      build: .
      volumes:
        - ./log:/usr/src/app/text.log
      container_name: simple-web-service


